theme: jekyll-theme-slate
title: MSSPOPowerUser - Training - SharePoint Online Power User
description: Companion material and resources for the course 'SharePoint Online Power User' delivery by Ricardo Cabral 
relative_links:
  enabled: true
  collections: true
include:
  - README.md
